### ISSUE TITLE
Superiors table makes person own superior officer  + has duplicate entries

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#359]
Some display errors have appeared in the superiors tables in person records:

https://whowasincommand.com/en/person/detail/630/
https://whowasincommand.com/en/person/detail/631/
https://whowasincommand.com/en/person/detail/752/

1. A person cannot be their own superior officer. In some records, the first row of data in a person's superiors table is that person. For example:

https://whowasincommand.com/en/person/detail/630/

Person:  `Usman Akila Gwary`
Superiors table:
![whowasincommand](https://user-images.githubusercontent.com/2115933/33161077-13cd53e4-d019-11e7-9610-cf1310d6f635.png)

I've also seen the issue in these records:
https://whowasincommand.com/en/person/detail/630/
https://whowasincommand.com/en/person/detail/631/
https://whowasincommand.com/en/person/detail/752/

2. Duplicate of complete superiors list

After naming a person as their own commander, the superiors list is then repeated:
https://whowasincommand.com/en/person/detail/631/

![whowasincommand](https://user-images.githubusercontent.com/2115933/33161253-117de6ac-d01a-11e7-8e95-925b0095b21a.png)

**Comment by jeancochrane** [comment]
Strange. If you're only just seeing this now, I bet one of my recent changes to this table (or maybe even the importer) must have introduced this.

**Comment by tlongers** [comment]
Yeah, I noticed it after the recent importer/deployment pipeline changes.

**Comment by jeancochrane** [comment]
This was a real doozy to debug. There's a lot of logic that goes into generating those tables... thanks for hanging in there! 

631 and 752 were both caused by an off-by-one error: we were checking for overlap in command using `<=` and `>=`, and since those people had been promoted to units that were superior to their previous unit (meaning they had the same day for `last_cited` on the subordinate and `first_cited` on the superior unit), they erroneously appeared to be superiors/subordinates of themselves. Both should be fully fixed in https://github.com/security-force-monitor/sfm-cms/commit/d151fab438bd3096ba719e3e9c284bcbacfac33d.

https://whowasincommand.com/en/person/detail/630/ is a little more complicated. Not only does there seem to be overlap between their post at `Anambra State Police Command` and their first post at `Zone 9 Police Command`, which amounts to a promotion (meaning that in the data, they really _are_ a superior/subordinate of themselves for the duration of that overlap); but that person appears to have a duplicate, overlapping posting in the same position at `Zone 9 Police Command`:

![usman](https://user-images.githubusercontent.com/14170650/33458959-e0b0a076-d5ed-11e7-951a-181a654cf86b.png)


This is a pretty confusing career history, so I'm wondering if the problem is in the importer or in the source data. I'm having trouble reading the source, do you think you can verify it?

**Comment by tlongers** [comment]
Jean, thanks for the clear explanation 👍 

Ok, `Zone 9 Police Command` is  is the expert domain of @tonysecurityforcemonitor :) We 

We can probably resolve this with a little more research on the `person` record, and I have some new data for him in the `minimonitor`, but we also need to introduce checks in the data entry to detect and flag situations like this.

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - thanks for flagging. I think this an answer to this thread... but perhaps not.

For the specifics of this person... I'm now realizing the error remains! :(

But for the broader point of: can someone be their own superior... the answer is yes

Depending on the organizational hierarchy, there could be situations where someone is their own superior officer. This will occur occasionally when 1) someone holds multiple posts which do not make sense to merge into a single post, and when those postings technically have hierarchical relationships to one another or 2) someone holds multiple posts which could be merged, but remain separate to allow us to more accurately capture situations involving other people/orgs.

1)
An easy example of this is the org 'President of the Federal Republic of Nigeria' and 'Armed Forces Council'. We want these two orgs to exist as they play different roles in relation to the armed forces (President as final unit at the top of the chain of command, whereas the Armed Forces Council plays an important, but subordinate, administrative role). The person who is President is the 'commander' of both organizations (the president is the Chairman or commander of the Armed Forces Council). Hierarchically, the org 'President of the Federal Republic of Nigeria' is the parent of 'Armed Forces Council', so they are technically their own commander. This isn't an ideal situation... but it's difficult given the multiple roles people can have simultaneously.  

2)
The 'Nigerian Army Headquarters' is an example where we have broken it out from the parent 'Nigerian Army', even though the same person is the commander of both organizations. Partly this is due to role that the Nigerian Army Headquarters plays vis a vis other parts of the security forces, and partly as it allows us easily incorporate people who are part of the army, but do not have a clearly identified relationship to a specific unit as they can be a member of the overall Nigerian Army.

(I'll point out that this isn't always the case depending on the structure of the security forces - for instance for Mexico the structure of SEDENA makes it difficult to have the "Army" as an organization since the head of SEDENA is technically the head of the army and the air force, and the Air Force has a specific person who is the commander of the Air Force, whereas the Mexican Army doesn't have an equivalent, since the head of SEDENA generally plays that role).

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - OK and now I've fixed the issue with that person as well - new version of data in DM shared folder for @evz to look at tomorrow :)

**Comment by tlongers** [comment]
@tonysecurityforcemonitor back to this interesting one again - any sign that we have encountered this again, or that we have had to address it within the source data?
