### ISSUE TITLE
Pen icon appears on read only view of person postings table 

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-cms#430]
On staging:

`~/en/person/view/19cfa251-2df7-49b7-88ff-df187e584b92/`

Clicking the pen icon sends the user to a log-in page. However, the pen icon shouldn't be visible, nor the function available to a non-logged in user.

<img width="723" alt="screen shot 2018-09-19 at 11 18 20" src="https://user-images.githubusercontent.com/2115933/45747510-f406b380-bbfd-11e8-8453-913b7413a335.png">

In some cases, a row is also highlighted in blue. For example:

`~/en/person/view/19cfa251-2df7-49b7-88ff-df187e584b92/`

![image](https://user-images.githubusercontent.com/2115933/45747884-0cc39900-bbff-11e8-8102-f334aebd99e1.png)

**Comment by tlongers** [comment]
Is this a deliberately created edit shortcut then?

**Comment by evz** [comment]
This was fixed by the [same commit](71f5aa4f9e85ca48f2846795bfe9a117904ee5ff) where I fixed #425 (since it's in the same template). I just went ahead and hid those links for non-logged in users.

**Comment by tlongers** [comment]
Thanks. It's a nice optimisation idea though.

**Comment by tlongers** [comment]
Fixed.

**Comment by tlongers** [comment]
Re-opening. There's still an issue around this area. In some records, guest users will see blue highlighting on the  "Postings" section of a record:

![image](https://user-images.githubusercontent.com/2115933/48409695-79a56c00-e734-11e8-9246-7ea1820df17b.png)

`~/en/person/view/6086fda5-9984-4657-a873-5cc08ca41a11/` (record for `Alhaji Mohammed Murtala Abbas`)

Looking at the same record, the logged-in user will also see the blue background as well as (correctly) a edit/pencil icon:

![image](https://user-images.githubusercontent.com/2115933/48409792-bc674400-e734-11e8-8e1d-fe7b11221a8e.png)

Expected behaviour in this view is not to see the blue background at all.
